media:
  - name: images
    label: Images
    input: projectghostsite/assets/images
    output: /projectghostsite/assets/images 
    extensions: [ jpg, png, webp ]
  - name: files
    label: Files
    input: assets/files
    output: /assets/files
    categories: [ document ]
content:
  - label: Home Page
    path: about.md
    name: homepage
    type: file
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }, required: true}
      - { name: body, label: Body, type: rich-text, hidden: true }
      - { name: meta_description, label: Meta Description, type: string, options: { maxlength: 180 }}
      - { name: meta_title, label: Meta Title, type: string, options: { maxlength: 120 }}
      - { name: subscribe, label: Subscribe, type: boolean, default: false, hidden: true }
      
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: "{primary}.md"
    view: 
      fields: [ title, published, date ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label: Comments, type: boolean, default: false, hidden: true }
      - { name: description, label: Description, type: string, options: { maxlength: 160 }}
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }

  - name: authors
    label: Authors
    type: collection
    path: _authors
    view: 
      fields: [ short_name, name, position ]
    fields:
      - { name: short_name, label: Short Name, type: string }
      - { name: name, label: Name, type: string }
      - { name: position, label: Position, type: string }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }
  